# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yardstick}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Kubb"]
  s.date = %q{2011-03-19}
  s.default_executable = %q{yardstick}
  s.email = %q{dan.kubb@gmail.com}
  s.executables = ["yardstick"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/yardstick",
    "lib/yardstick.rb",
    "lib/yardstick/autoload.rb",
    "lib/yardstick/cli.rb",
    "lib/yardstick/core_ext/object.rb",
    "lib/yardstick/measurable.rb",
    "lib/yardstick/measurement.rb",
    "lib/yardstick/measurement_set.rb",
    "lib/yardstick/method.rb",
    "lib/yardstick/ordered_set.rb",
    "lib/yardstick/processor.rb",
    "lib/yardstick/rake/measurement.rb",
    "lib/yardstick/rake/verify.rb",
    "lib/yardstick/rule.rb",
    "lib/yardstick/rule_set.rb",
    "lib/yardstick/yard_ext.rb",
    "spec/public/yardstick/cli_spec.rb",
    "spec/public/yardstick/measurement_set_spec.rb",
    "spec/public/yardstick/measurement_spec.rb",
    "spec/public/yardstick/method_spec.rb",
    "spec/public/yardstick/rake/measurement_spec.rb",
    "spec/public/yardstick/rake/verify_spec.rb",
    "spec/public/yardstick_spec.rb",
    "spec/rcov.opts",
    "spec/semipublic/yardstick/rule_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/ci.rake",
    "tasks/heckle.rake",
    "tasks/metrics.rake",
    "tasks/spec.rake",
    "tasks/yard.rake",
    "tasks/yardstick.rake",
    "yardstick.gemspec"
  ]
  s.homepage = %q{http://github.com/dkubb/yardstick}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{yardstick}
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A tool for verifying YARD documentation coverage}
  s.test_files = [
    "spec/public/yardstick/cli_spec.rb",
    "spec/public/yardstick/measurement_set_spec.rb",
    "spec/public/yardstick/measurement_spec.rb",
    "spec/public/yardstick/method_spec.rb",
    "spec/public/yardstick/rake/measurement_spec.rb",
    "spec/public/yardstick/rake/verify_spec.rb",
    "spec/public/yardstick_spec.rb",
    "spec/semipublic/yardstick/rule_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yard>, ["~> 0.6.5"])
      s.add_development_dependency(%q<flay>, ["~> 1.4.2"])
      s.add_development_dependency(%q<flog>, ["~> 2.5.1"])
      s.add_development_dependency(%q<metric_fu>, ["~> 2.1.1"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_development_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.1"])
    else
      s.add_dependency(%q<yard>, ["~> 0.6.5"])
      s.add_dependency(%q<flay>, ["~> 1.4.2"])
      s.add_dependency(%q<flog>, ["~> 2.5.1"])
      s.add_dependency(%q<metric_fu>, ["~> 2.1.1"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_dependency(%q<rspec>, ["~> 1.3.1"])
    end
  else
    s.add_dependency(%q<yard>, ["~> 0.6.5"])
    s.add_dependency(%q<flay>, ["~> 1.4.2"])
    s.add_dependency(%q<flog>, ["~> 2.5.1"])
    s.add_dependency(%q<metric_fu>, ["~> 2.1.1"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
    s.add_dependency(%q<roodi>, ["~> 2.1.0"])
    s.add_dependency(%q<rspec>, ["~> 1.3.1"])
  end
end

